name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $ofegousse1
          password: $dckr_pat_0PC7bGl0ecQv7L_5tJXt_pvxBrY
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: feomar04/githubactions:${{ github.sha }}
          
      
